<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>DcNotify.IntegrationTests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\DcNotify\DcNotify.csproj" />
    <ProjectReference Include="..\DcNotify.TestSupport\DcNotify.TestSupport.csproj" />
  </ItemGroup>
</Project>
